# Hexo Configuration
## Docs: https://hexo.io/docs/configuration.html
## Source: https://github.com/hexojs/hexo/

# Site
title: Oleg Korol's Blog
subtitle: ...about full-stack JavaScript development and tech in general
author: Oleg Korol
language: English
timezone:

# URL
## If your site is put in a subdirectory, set url as 'http://yoursite.com/child' and root as '/child/'
url: https://olegkorol.github.io
root: /
permalink: :year/:month/:day/:title/
permalink_defaults:

#Custom Setting Start

# Site settings
SEOTitle: Oleg Korol's Blog
header-img: img/home-bg.jpg
email: oleg@olegkorol.de
description: "Oleg Korol's personal blog. Thoughts on Web Deveopment. JavaScript."
keyword: "oleg korol, javascript, web, development, frontend, backend"


# SNS settings
# RSS: false
github_username:    olegkorol
twitter_username:   oleg_korol
facebook_username:  olegkorol.de
linkedin_username:  oleg-korol-a8057628

# Build settings
anchorjs: true    # if you want to customize anchor, check out line:181 of `post.html`


# Disqus settings
disqus_username: olegkorol

# Analytics settings
#  Google Analytics:
ga_track_id: 'UA-66639263-1'  # Format: UA-xxxxxx-xx
ga_domain: olegkorol.de


# Sidebar settings
sidebar: true                           # whether or not using Sidebar.
sidebar-about-description: "Learning addict, specially around the JavaScript ecosystem. My current stack includes Angular 2, NodeJS (Express/Koa), MongoDB and MySQL (Sequellize)"
sidebar-avatar: img/avatar.jpg      # use absolute URL, seeing it's used in both `/` and `/about/`


# Featured Tags
featured-tags: true                     # whether or not using Feature-Tags
featured-condition-size: 1              # A tag will be featured if the size of it is more than this condition value


# Friends
friends: [
    {
        title: "Kaijun's Blog",
        href: "http://blog.kaijun.rocks"
    },{
        title: "Hux Blog",
        href: "http://huangxuan.me"
    }
]


#Custom Setting End



# Directory
source_dir: source
public_dir: public
tag_dir: tags
archive_dir: the_archive
category_dir: categories
code_dir: downloads/code
i18n_dir: :lang
skip_render:

# Writing
new_post_name: :title.md # File name of new posts
default_layout: post
titlecase: false # Transform title into titlecase
external_link: true # Open external links in new tab
filename_case: 0
render_drafts: false
post_asset_folder: true
relative_link: false
future: true
highlight:
  enable: true
  line_number: true
  auto_detect: true
  tab_replace:

# Category & Tag
default_category: uncategorized
category_map:
tag_map:

# Date / Time format
## Hexo uses Moment.js to parse and display date
## You can customize the date format as defined in
## http://momentjs.com/docs/#/displaying/format/
date_format: YYYY-MM-DD
time_format: HH:mm:ss

# Pagination
## Set per_page to 0 to disable pagination
per_page: 10
pagination_dir: page

# Extensions
## Plugins: https://hexo.io/plugins/
## Themes: https://hexo.io/themes/
theme: huxblog

# Deployment
## Docs: https://hexo.io/docs/deployment.html
deploy:
  type: git
  repo: https://github.com/olegkorol/olegkorol.github.io
  branch: master


