# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Oleg Korol
description: > # this means to ignore newlines until "baseurl:"
  Oleg Korol's personal site and blog.
repository: https://github.com/olegkorol/olegkorol.github.io
baseurl: /  # the subpath of your site, e.g. /blog
url: https://olegkorol.github.io  # the base hostname & protocol for your site

# Build settings
markdown: kramdown

# Sass settings
sass:
  style: compressed

# Theme settings
theme_mode: markdown  # choices are: 'dark', 'standard', 'markdown'

# Customizations
your_name: Oleg Korol
email: oleg@olegkorol.de

navigation:
  - text: Home
    url: /
  - text: Blog
    url: /blog
  - text: About
    url: /about
  - text: Projects
    url: /projects

projects:
  - name: ng2-reddit-clone
    description: A Reddit clone created to test Angular 2.
    link: https://olegkorol.github.io/ng2-reddit-clone
    image: https://avatars1.githubusercontent.com/u/13587499?v=3&u=4649cc013a8405dc4f1ec94c26b9641c6ee12e06&s=400

social:
  - service: github
    username: olegkorol
    link: https://github.com/olegkorol
  - service: twitter
    username: oleg_korol
    link: https://twitter.com/oleg_korol

# Plugins
gems:
  - jekyll-seo-tag
